name: PowerShell tip submission
description: Submit a new PowerShell tip to be included in the tiPS module
title: "New Tip Submission - Ignore this field"
labels: ["automation-new-tip-do-not-use "]
body:
  - type: markdown
    attributes:
      value: |
        THIS FORM DOES NOT WORK YET! IT IS STILL A WORK IN PROGRESS!
        Please do not use it yet. It is here for reference only.

        Thanks for submitting a new PowerShell tip! Please fill in all required fields below.
        The more information you provide, the easier it will be for us to review and include your tip.

  - type: input
    id: title
    attributes:
      label: Tip Title (required)
      description: A concise title for your tip (max 75 characters)
      placeholder: e.g. Use `-Filter` with `Get-ChildItem` to speed up file searches
    validations:
      required: true

  - type: textarea
    id: tipText
    attributes:
      label: Tip Text (required)
      description: Detailed explanation of the tip. Be clear and concise.
      placeholder: Write your tip description here...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code (optional)
      description: Provide a working PowerShell example that demonstrates your tip.
      render: powershell
      placeholder: Your example code here...

  - type: input
    id: url1
    attributes:
      label: URL 1 (optional)
      description: URL with additional information (must start with http:// or https://)
      placeholder: https://example.com

  - type: input
    id: url2
    attributes:
      label: URL 2 (optional)
      description: URL with additional information (must start with http:// or https://)
      placeholder: https://example.com

  - type: input
    id: url3
    attributes:
      label: URL 3 (optional)
      description: URL with additional information (must start with http:// or https://)
      placeholder: https://example.com

  - type: dropdown
    id: category
    attributes:
      label: Category (required)
      description: Select the category that best fits your tip.
        - Community - Social events and community resources. e.g. PowerShell Summit, podcasts, etc.
        - Editor - Editor tips and extensions. e.g. VSCode, ISE, etc.
        - Module - Modules and module tips. e.g. PSScriptAnalyzer, Pester, etc.
        - NativeCmdlet - Native cmdlet tips. e.g. Get-Process, Get-ChildItem, Get-Content, etc.
        - Performance - Tips to improve runtime performance. e.g. foreach vs ForEach-Object, ForEach-Object -Parallel, etc.
        - Security - Security tips. e.g. ExecutionPolicy, Constrained Language Mode, passwords, etc.
        - Syntax - Syntax tips. e.g. splatting, pipeline, etc.
        - Terminal - Terminal shortcuts and tips. e.g. PSReadLine, Windows Terminal, ConEmu, etc.
        - Other - Tips that don't fit into any of the other categories.
      options:
        - Community
        - Editor
        - Module
        - NativeCmdlet
        - Performance
        - Security
        - Syntax
        - Terminal
        - Other
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Author (optional)
      description: Your name and/or username. Leave blank if you prefer to remain anonymous.
      placeholder: e.g. Daniel Schroeder (deadlydog)

  - type: input
    id: expiryDate
    attributes:
      label: Expiry Date (optional)
      description: Date when the tip should expire (format of YYYY-MM-DD). Mostly applicable when promoting a community event on a specific date. Leave blank for no expiry.
      placeholder: '2025-10-25'

  - type: markdown
    attributes:
      value: |
        By submitting this tip, you agree to make it available under the project's license.
        The tip's CreatedDate will be set to the date when it's accepted, and ExpiryDate will
        be set to the maximum date unless otherwise specified.
