name: Process New PowerShell Tip

on:
  issues:
    types: [opened]

jobs:
  process-new-tip:
    if: contains(github.event.issue.labels.*.name, 'automation-new-tip-do-not-use')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract tip information from issue
        id: extract-tip
        shell: pwsh
        run: |
          $issue = ConvertFrom-Json '${{ toJson(github.event.issue) }}'
          $body = $issue.body

          # Define the variables to extract the GitHub issue fields into.
          [string] $tipTitle = [string]::Empty
          [string] $tipText = [string]::Empty
          [string] $tipExample = [string]::Empty
          [string] $tipCategory = [string]::Empty
          [string[]] $tipUrls = @()
          [string] $tipAuthor = [string]::Empty
          [string] $tipExpiryDate = [string]::Empty

          # Extract the data from the markdown representation of the issue.
          # GitHub Forms generates structured markdown with specific section headers we can match against.

          # Extract Title
          if ($body -match '### Title \(required\)\s+([^\r\n]+)') {
            $tipTitle = $Matches[1].Trim()
            Write-Output "Extracted Title: $tipTitle"
          }

          # Extract Tip Text
          if ($body -match '### Tip Text \(required\)\s+([\s\S]*?)(?=###|$)') {
            $tipText = $Matches[1].Trim()
            Write-Output "Extracted Tip Text: $($tipText.Substring(0, [Math]::Min(30, $tipText.Length)))..."
          }

          # Extract Example Code
          if ($body -match '### Example Code \(optional\)\s+```powershell\s+([\s\S]*?)```') {
            $tipExample = $Matches[1].Trim()
            Write-Output "Example code extracted with length: $($tipExample.Length)"
          }

          # Extract URLs (up to 3)
          if ($body -match '### URL 1 \(optional\)\s+([^\r\n]+)') {
            $url = $Matches[1].Trim()
            if (-not [string]::IsNullOrWhiteSpace($url)) {
              $tipUrls += $url
              Write-Output "Extracted URL 1: $url"
            }
          }

          if ($body -match '### URL 2 \(optional\)\s+([^\r\n]+)') {
            $url = $Matches[1].Trim()
            if (-not [string]::IsNullOrWhiteSpace($url)) {
              $tipUrls += $url
              Write-Output "Extracted URL 2: $url"
            }
          }

          if ($body -match '### URL 3 \(optional\)\s+([^\r\n]+)') {
            $url = $Matches[1].Trim()
            if (-not [string]::IsNullOrWhiteSpace($url)) {
              $tipUrls += $url
              Write-Output "Extracted URL 3: $url"
            }
          }

          # Extract Category
          if ($body -match '### Category \(required\)\s+([^\r\n]+)') {
            $fullCategory = $Matches[1].Trim()
            # Extract just the category name (before any parentheses)
            if ($fullCategory -match '^([^(]+)') {
              $tipCategory = $Matches[1].Trim()
              Write-Output "Extracted Category: $tipCategory"
            }
          }

          # Extract Author
          if ($body -match '### Author \(optional\)\s+([^\r\n]+)') {
            $tipAuthor = $Matches[1].Trim()
            Write-Output "Extracted Author: $tipAuthor"
          }

          # Set current date as CreatedDate.
          $tipCreatedDate = Get-Date -Format "yyyy-MM-dd"

          # Get the file contents to use by dot-sourcing the file with the function to call.
          . $GITHUB_WORKSPACE/.github/workflows/ProcessNewPowerShellTipIssueFunctions.ps1
          $getFileContentsParameters = @{
            TipCreatedDate = $tipCreatedDate
            TipTitle = $tipTitle
            TipText = $tipText
            TipExample = $tipExample
            TipUrls = $tipUrls
            TipCategory = $tipCategory
            TipAuthor = $tipAuthor
            TipExpiryDate = $tipExpiryDate
          }
          [string] $fileContent = New-PowerShellTipFileContents @getFileContentsParameters

          # Create branch name and filename.
          $branchName = "new-tip/issue-$($issue.number)"
          $fileName = "$tipCreatedDate-$($tipTitle.ToLower() -replace '[^a-z0-9]', '-' -replace '-+', '-').ps1"
          $filePath = "src/PowerShellTips/$fileName"

          # Output variables for next steps.
          "branch_name=$branchName" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          "file_name=$fileName" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          "file_path=$filePath" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          "file_content=$fileContent" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          "issue_number=$($issue.number)" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
          "tip_title=$tipTitle" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Create branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b "${{ steps.extract-tip.outputs.branch_name }}"
        shell: bash

      - name: Create tip file
        run: |
          # Ensure directory exists
          $directory = Split-Path -Parent "${{ steps.extract-tip.outputs.file_path }}"
          if (-not (Test-Path $directory)) {
            New-Item -ItemType Directory -Path $directory -Force
          }

          # Create the file
          Set-Content -Path "${{ steps.extract-tip.outputs.file_path }}" -Value "${{ steps.extract-tip.outputs.file_content }}"
        shell: pwsh

      - name: Push changes and create PR
        run: |
          git add "${{ steps.extract-tip.outputs.file_path }}"
          git commit -m "Add new PowerShell tip: ${{ steps.extract-tip.outputs.tip_title }}"
          git push --set-upstream origin "${{ steps.extract-tip.outputs.branch_name }}"

          # Create PR
          gh pr create \
            --title "New PowerShell Tip: ${{ steps.extract-tip.outputs.tip_title }}" \
            --body "This PR adds a new PowerShell tip submitted via issue #${{ steps.extract-tip.outputs.issue_number }}." \
            --label "enhancement" \
            --label "new-tip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Add comment to issue
        run: |
          gh issue comment "${{ steps.extract-tip.outputs.issue_number }}" --body "Thanks for your submission! I've created a pull request with your tip. You can view it here: ${{ github.server_url }}/${{ github.repository }}/pull/$(gh pr list --head ${{ steps.extract-tip.outputs.branch_name }} --json number --jq '.[0].number')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      - name: Close issue
        run: |
          gh issue close "${{ steps.extract-tip.outputs.issue_number }}" --comment "This issue has been processed and a pull request has been created with your tip."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
